platform:
  - x64
environment:
  global:
    APPVEYOR_OS_NAME: windows
    GOPATH: c:\gopath
    BINTRAY_PATH: coyim/coyim-bin/coyim-bin/windows
    BINTRAY_USER:
      secure: h9afmV6qW6+IVP0M8ugyrg==
    BINTRAY_APIKEY:
      secure: X2eHRabnZpixA+Oub12e3V+36sdrOTvbL+/dAB0pqWYGWYXqi+lcw5bLxjEuLTiZ
  matrix:
    #- MSYS2_ARCH: x86_64
    #  MSYS2_BITS: 64
    #  MSYSTEM: MSYS2
    #  METHOD: ci
    #- MSYS2_ARCH: i686
    #  MSYS2_BITS: 32
    #  MSYSTEM: MINGW32
    #  METHOD: cross
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      METHOD: cross
      MSYS2_BASEVER: 20180531
install:
  - .\ci\install-deps-windows.bat
build_script:
  - echo 'path: %MSYS_PATH%'
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim && make win-ci-deps"'
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/coyim/coyim && make build-gui-win"'
after_build:
  - .\ci\build-windows-bundle.bat
artifacts:
  - path: coyim.zip
    name: CoyIM
# deploy:
# - provider: BinTray
#   username: olabini
#   api_key:
#     secure: X2eHRabnZpixA+Oub12e3V+36sdrOTvbL+/dAB0pqWYGWYXqi+lcw5bLxjEuLTiZ
#   subject: coyim
#   repo: coyim-bin
#   package: windows
#   version: $(APPVEYOR_REPO_TAG_NAME)
#   publish: true
#   override: true
#   explode: false
#   on:
#     APPVEYOR_REPO_TAG: true
deploy_script:
  - SET APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_BRANCH%
  - if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  - curl -T coyim.zip -u "%BINTRAY_USER%:%BINTRAY_APIKEY%" "https://api.bintray.com/content/coyim/coyim-bin/coyim-bin/%APPVEYOR_BUILD_VERSION%/%APPVEYOR_BUILD_VERSION%/windows/CoyIM.zip?override=1&publish=1"
