dist: trusty
sudo: required
language: go
branches:
  except:
    - windows
go:
  - tip
  - 1.8
  - 1.7.5
  - 1.6.4

services:
  - docker

matrix:
  include:
    - go: 1.7.5
      env: RELEASE=true
      os: linux
    - go: 1.7.5
      env: RELEASE=true
      os: osx
  allow_failures:
    - os: osx
    - go: tip
    - env: RELEASE=true
  fast_finish: true

before_install:
  - "export DISPLAY=:99.0"
  - ci/install-deps-${TRAVIS_OS_NAME:-linux}
  - "export COYIM_PATH=$(pwd)/bin/coyim"
install: make deps-dev
script: make -C ci/

before_deploy: ci/release
deploy:
  on:
    all_branches: true
    condition: '"$RELEASE" = "true" && ( -n "$TRAVIS_TAG" || "$TRAVIS_BRANCH" = "master" )'
  provider: bintray
  file: ci/bintray.json
  user:
    secure: LkuJiB6xuPIMB0Nq1z11Go/4Vo1hP4TUMAe16e3kbeLhZ4DsdQfxkCO1mCM4448rcMtzrHsCUVFoW5HCzNcbfvlzox9065yAGjRP00IK1g1ohqnRYAyQkAf2YKp9Rw+RGojk6sQe88yfcRIgltRXDZFq0CaF0AF9ytDy1wMQj6231Xr2mMcIr8Mr8zUkpw7rG/NfFOGpA19NX58JcJ1fVjyPPvLGHYpz3BbIU1gsUe2OAdqwJFVr00dXNg5U6F8tq8kTL8v9nKl3vITzQe5MRh8HDhQmBQDm8hOw9d0fSKw7e/m237kM3eAVdVUN/0f0D+6/7OPMuMN2aTbj27U1PiMx/G35khy9ll99Qt/KOzRlrP/nhGN+FouGrun5zUYgNLIux+rGtlO4N26kBOw1Zbcdjrsa39eZcWuHkX7M3U/zEFT58cRBvJDo7VGuHefMbmAeEkAsET3uqcHjJsGscJThPWbJSeU4z4udOvkF3ETshXjU9ywLf/HCy3m9BDqCor6r+d643246zJUrAhMD2FsPsEVukbiQ3dRFk9EZd7k4U6tPsOGiSbgfsZSAZWbdJ9SpSc2S11b4NmS/5k+cXOwkLTRJIKJJMLwVHIM8QQ52wvInIw3OPqojDpqI3NTnOJYh+rkoNEIbsnMa3VAZE3WsP+PC/sDwKLCcW6+psa4=
  key:
    secure: TssP9ek1VXehTuJ7u3K2OE5G99tgooHwF2/sSJTZDPk3+8DAliZ+5GZI+K6e+avKn11bVcMGoQ23StngOp5BHYu2/Z9A5A4TENi8xwYzXzsFYGxYlvfk8lvE8Vl5JpTk2/XvBg+80O672TxAFthKddARSoDx8Zlb1Ya1ae4O87hVSFDuzrQGoy+fSZjRctmCFlwB2kcYQdcXSjbcGamdFLOSHQ176abtcQBNFBeRzeRQNAz3Z/2ZkS1M7858bVWnuMcQlYaKXZ3eyG+Hp+wYLDL35NgPigEYqOZE3b6YFTsjniJ4sHt9SbLEHKUBUWCLjv64zyo/vyp5Yp6vGbZqTvD1gypIXyAMkszjmVsgWSDZLYKYzQGeAXcvHDAK7G5e7Nn+m79Y2bMlTwN4qSj3N0qA9arrgiWPjr6bWtmx3ZKGgC0nlnnQtsR20ivbG5+2+AlDFO0O55DZxxDHBd2sAejx9FF0IageIqHXP7Opr6h0/FFHi4BqnDxo+EanhBNd3qt4Onft3zFxFiJZg8vkIwRYX2pKd4mPMQ7df7XTS2hW0lCe7EqEpSqL6qWTdYG0ZxkIl2cpa9Ll8stHJybvQot8gA6ZpOvyEbY8OzQNKu6KNap0l5cpP0tiQcIK6I6NbNJFMHlRwn/uxy+KY/ukCrzpeRn7NBB4tjQN6stD6ns=
  dry-run: false
