os: osx
osx_image: xcode12.2
language: go

branches:
  except:
    - main

git:
  depth: false
  quiet: true

go:
  - "1.14.x"

services:
  - docker

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

before_cache:
  - brew cleanup
  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete

addons:
  homebrew:
    packages:
    - gsettings-desktop-schemas
    - hicolor-icon-theme
    - shared-mime-info
    - gtk+3
    - gtk-mac-integration
    - adwaita-icon-theme
    - fileicon
    update: true

before_install:
  - "export DISPLAY=:99.0"
  # - npm install --global appdmg
  # - brew uninstall --ignore-dependencies --force java
  # - brew uninstall --ignore-dependencies --force openjdk
  # - brew cask uninstall java
  # - travis_wait 60 brew update
  # - travis_wait 60 brew install docbook
  # - travis_wait 60 brew install docbook-xsl
  # - travis_wait 60 brew install bison
  # - travis_wait 60 brew install meson
  # - travis_wait 60 brew install cairo
  # - travis_wait 60 brew install atk
  # - travis_wait 60 brew install gdk-pixbuf
  # - travis_wait 60 brew install gobject-introspection
  # - travis_wait 60 brew install gsettings-desktop-schemas
  # - travis_wait 60 brew install hicolor-icon-theme
  # - travis_wait 60 brew install libepoxy
  # - travis_wait 60 brew install intltool
  # - travis_wait 60 brew install fribidi
  # - travis_wait 60 brew install harfbuzz
  # - travis_wait 60 brew install cmake
  # - travis_wait 60 brew install libssh2
  # - travis_wait 100 brew install rust
  # - travis_wait 60 brew install librsvg
  # - travis_wait 60 brew install pango
  # - travis_wait 100 brew install gtk+3
  # - travis_wait 60 brew install adwaita-icon-theme
  # - travis_wait 60 brew install gnome-icon-theme
  # - travis_wait 60 brew install shared-mime-info
  # - travis_wait 60 brew install fileicon
  # - travis_wait 60 brew install gtk-mac-integration
  # - "export DISPLAY=:99.0"
  # - npm install --global appdmg

install:
  - make -C ci/ deps

script:
  - make -C ci/ clean-mac-bundle
  - travis_wait 45 make build-gui
  - travis_wait 45 make -C ci/ make-mac-bundle
  - travis_wait 45 make -C ci/ make-dmg
  - travis_wait 45 make -C ci/ make-gui-for-release

deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
